use job_match_api;
INSERT INTO cities(name) VALUES
('Aheloy'),
('Ahtopol'),
('Aksakovo'),
('Alfatar'),
('Anton'),
('Antonovo'),
('Apriltsi'),
('Ardino'),
('Asen'),
('Asenovgrad'),
('Aytos'),
('Balchik'),
('Balgarevo'),
('Banite'),
('Bansko'),
('Bata'),
('Batak'),
('Batanovtsi'),
('Belene'),
('Belitsa'),
('Belogradchik'),
('Beloslav'),
('Belovo'),
('Berkovitsa'),
('Blagoevgrad'),
('Boboshevo'),
('Bobov Dol'),
('Bolyarovo'),
('Borino'),
('Borovan'),
('Borovo'),
('Botevgrad'),
('Bov'),
('Boychinovtsi'),
('Boynitsa'),
('Bozhurishte'),
('Bratsigovo'),
('Bregovo'),
('Breznik'),
('Brezovo'),
('Brusartsi'),
('Buhovo'),
('Burgas'),
('Byala'),
('Byala Cherkva'),
('Byala Slatina'),
('Chavdar'),
('Chelopech'),
('Chepelare'),
('Chernomorets'),
('Cherven Bryag'),
('Chiprovtsi'),
('Chirpan'),
('Chuprene'),
('Dalgopol'),
('Debelets'),
('Devin'),
('Devnya'),
('Dimitrovgrad'),
('Dimovo'),
('Dobrich'),
('Dolna Banya'),
('Dolna Mitropolia'),
('Dolni Chiflik'),
('Dolni Dabnik'),
('Dospat'),
('Dragoman'),
('Drenovets'),
('Dryanovo'),
('Dulovo'),
('Dunavtsi'),
('Dupnitsa'),
('Dve Mogili'),
('Dzhebel'),
('Elena'),
('Elhovo'),
('Elin Pelin'),
('Elkhovo'),
('Etropole'),
('Gabrovo'),
('Gara Hitrino'),
('Garmen'),
('General Toshevo'),
('Glavinitsa'),
('Godech'),
('Gorichevo'),
('Gorna Malina'),
('Gorna Oryahovitsa'),
('Gotse Delchev'),
('Gramada'),
('Gulyantsi'),
('Gurkovo'),
('Gyovren'),
('Gŭlŭbovo'),
('Hadzhidimovo'),
('Harmanli'),
('Haskovo'),
('Hayredin'),
('Hisarya'),
('Ihtiman'),
('Iskar'),
('Isperih'),
('Ivanovo'),
('Ivaylovgrad'),
('Kalofer'),
('Kaloyanovo'),
('Kameno'),
('Kaolinovo'),
('Kardzhali'),
('Karlovo'),
('Karnobat'),
('Kaspichan'),
('Kavarna'),
('Kaynardzha'),
('Kazanlak'),
('Kermen'),
('Kilifarevo'),
('Kirkovo'),
('Kiten'),
('Klisura'),
('Knezha'),
('Kocherinovo'),
('Koprivshtitsa'),
('Kostinbrod'),
('Kotel'),
('Koynare'),
('Kozloduy'),
('Kresna'),
('Krichim'),
('Krivodol'),
('Krumovgrad'),
('Krushari'),
('Kubrat'),
('Kula'),
('Kyustendil'),
('Lakatnik'),
('Laki'),
('Lesichovo'),
('Letnitsa'),
('Levski'),
('Lom'),
('Lovech'),
('Loznitsa'),
('Lukovit'),
('Lyaskovets'),
('Lyubimets'),
('Madan'),
('Madzharovo'),
('Maglizh'),
('Makresh'),
('Malko Tarnovo'),
('Medkovets'),
('Medovene'),
('Mezdra'),
('Mineralni Bani'),
('Mirkovo'),
('Mizia'),
('Montana'),
('Nedelino'),
('Nesebar'),
('Nevestino'),
('Nikolaevo'),
('Nikopol'),
('Nova Zagora'),
('Novi Pazar'),
('Novo Selo'),
('Obzor'),
('Omurtag'),
('Opaka'),
('Oryahovo'),
('Panagyurishte'),
('Parvomay'),
('Parvomaytsi'),
('Pavel Banya'),
('Pavlikeni'),
('Pazardzhik'),
('Pernik'),
('Perushtitsa'),
('Peshtera'),
('Petrich'),
('Pirdop'),
('Pleven'),
('Pliska'),
('Plovdiv'),
('Polski Trambesh'),
('Pomorie'),
('Popovo'),
('Pordim'),
('Pravets'),
('Primorsko'),
('Provadia'),
('Radnevo'),
('Radomir'),
('Rakitovo'),
('Rakovski'),
('Ravda'),
('Razgrad'),
('Razlog'),
('Rila'),
('Roman'),
('Rudozem'),
('Ruen'),
('Ruse'),
('Ruzhintsi'),
('Sadovo'),
('Saedinenie'),
('Samokov'),
('Samuil'),
('Sandanski'),
('Sapareva Banya'),
('Sarafovo'),
('Sarnitsa'),
('Satovcha'),
('Senovo'),
('Septemvri'),
('Sevlievo'),
('Shabla'),
('Shipka'),
('Shumen'),
('Silistra'),
('Simeonovgrad'),
('Simitli'),
('Sitovo'),
('Slavyanovo'),
('Sliven'),
('Slivnitsa'),
('Slivo Pole'),
('Smolyan'),
('Smyadovo'),
('Sofia'),
('Sozopol'),
('Spasovo'),
('Sredets'),
('Stamboliyski'),
('Stara Kresna'),
('Stara Zagora'),
('Straldzha'),
('Strazhitsa'),
('Strelcha'),
('Strumyani'),
('Suhindol'),
('Sungurlare'),
('Suvorovo'),
('Sveti Vlas'),
('Svilengrad'),
('Svishtov'),
('Svoge'),
('Targovishte'),
('Tervel'),
('Teteven'),
('Tochilari'),
('Topolovgrad'),
('Topolovo'),
('Tran'),
('Troyan'),
('Tryavna'),
('Tsar Kaloyan'),
('Tsarevo'),
('Tsenovo'),
('Tutrakan'),
('Tvarditsa'),
('Ugarchin'),
('Valchedram'),
('Valchidol'),
('Varbitsa'),
('Varna'),
('Varshets'),
('Veliki Preslav'),
('Veliko Tŭrnovo'),
('Velingrad'),
('Venets'),
('Vetovo'),
('Vetrino'),
('Vidin'),
('Vratsa'),
('Yablanitsa'),
('Yakimovo'),
('Yakoruda'),
('Yambol'),
('Zavet'),
('Zelenikovo'),
('Zemen'),
('Zlataritsa'),
('Zlatitsa'),
('Zlatni Pyasatsi'),
('Zlatograd');